name: built_redux
version: 9.0.0
description: A state management library written in dart that enforces immutability
homepage: https://github.com/davidmarne/built_redux

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  built_collection: ^5.0.0
  built_value: ^8.0.6
  source_gen: ^1.0.1
  test: ^1.17.5

dev_dependencies:
  build_runner: ^2.0.4
  build_test: ^2.1.0
  built_value_generator: ^8.0.6
  build_web_compilers: ^3.0.0
  workiva_analysis_options: ^1.2.0
